

TARGET_LIN_VEL = 0.35   
TARGET_ANG_VEL = 0.50   
TARGET_REV_VEL = 0.20

FRONT_STOP_DIST    = 0.15 
FRONT_BLOCK_DIST   = 0.25  
FRONT_BLOCK_CLEAR_DIST = 0.30 
FRONT_CAUTION_DIST = 0.35  

OVERHEAD_DETECT_DIST = 1.00  
OVERHEAD_MARK_ENABLED = True    
OVERHEAD_MARK_MIN_PIXELS = 8  

OVERHEAD_CAM_HEIGHT_M      = 0.17  
OVERHEAD_ROBOT_CLEARANCE_M = 0.20  


CAUTION_LIN_VEL = 0.20  
CAUTION_ANG_VEL = 0.12  

WALL_TARGET_DIST = 0.35 
WALL_CLOSE_BAND  = 0.12 
WALL_LOST_DIST   = 0.80  
SIDE_DANGER_DIST = 0.03  
OMEGA_SMALL      = 0.22  

BLOCK_TIMEOUT  = 40   
REAR_SAFE_DIST = 0.25  


FRONT_BLOCK_TIMEOUT_STEPS  = 20    
FRONT_ESCAPE_REVERSE_STEPS = 25   
FRONT_ESCAPE_REVERSE_VEL   = -0.12 
FRONT_ESCAPE_TURN_OMEGA    = 0.8  


BLUE_HSV_LOWER   = [100, 150,  50]
BLUE_HSV_UPPER   = [140, 255, 255]
YELLOW_HSV_LOWER = [ 20, 100, 100]
YELLOW_HSV_UPPER = [ 35, 255, 255]
GREEN_HSV_LOWER  = [ 36, 100, 100]
GREEN_HSV_UPPER  = [ 86, 255, 255]

GREEN_PIXEL_RATIO  = 0.08 
TARGET_PIXEL_RATIO = 0.03 
GREEN_ROI_TOP_FRAC = 0.5  

COLUMN_HEIGHT_CM      = 125.0  
COLUMN_DIST_OFFSET_CM = 10.0   
COLUMN_TOP_STRIP_PX   = 50    

GREEN_DEPTH_MIN_VALID = 0.03 
GREEN_STOP_DIST    = 0.35  
GREEN_CAUTION_DIST = 0.75 


GREEN_MARK_ENABLED  = True   
GREEN_CAM_HEIGHT_M  = 0.17   
GREEN_CAM_X_OFFSET  = 0.03   
GREEN_MAX_PROJ_DIST = 1.2    
GREEN_MARK_MIN_PIXELS = 60   

POSE_LOG_PERIOD_STEPS = 50 


SLIP_ENC_ROT_RAD    = 0.01 
SLIP_GYRO_RATE_RADS = 0.05 

MAP_SIZE  = 300          
MAP_RES_M = 10.0 / 300.0 

LOGODDS_INIT = 1.0  
LOGODDS_FREE = -0.36 
LOGODDS_OCC  = 0.85  
LOGODDS_LOCK = 3.5   
LOGODDS_CLIP = 5.0   
MAP_LIDAR_MAX_RANGE_M = 3.5  

P_OCC  = 0.7  
P_FREE = 0.5  

CELL_FREE    = 0
CELL_OCC     = 1
CELL_UNKNOWN = 255
CELL_CLOSED  = 200 
CELL_GREEN   = 190  
CELL_BLUE    = 100  
CELL_YELLOW  = 150  

MAP_UPDATE_PERIOD_STEPS = 1    
MAP_UPDATE_MAX_OMEGA    = 5.0   

ASTAR_INFLATION_LEVELS = [4, 3, 2]  
ASTAR_EXPANSION_PIXELS = 3         
PATH_MIN_LENGTH_M      = 0.8        
ASTAR_SAFE_DISTANCE_PX = 5.0        
ASTAR_PENALTY_STRENGTH = 2.0        
ASTAR_HEURISTIC_WEIGHT = 1.2        
PLAN_BLOCK_UNKNOWN     = True      
ASTAR_FRONTIER_INFLATION = 4      
                                  


DWA_VELOCITY_SAMPLES = [0.1, 0.15, 0.2, 0.25, 0.3, 0.35]                    
DWA_ANGULAR_SAMPLES  = [0, 2, 2.5, -2, -2.5, 3, -3, 3.5, -3.5, 4.5, -4.5]   
DWA_ROLLOUT_STEPS    = 10    

DWA_HEADING_WEIGHT   = 4.0   
DWA_DISTANCE_WEIGHT  = 3.5   
DWA_SPEED_WEIGHT     = 0.5  
DWA_CLEARANCE_WEIGHT = 2.0   

DWA_ROBOT_CLEAR_PX   = 3.5   
                             
DWA_CLEAR_PENALTY    = 3.5   

FOLLOW_GOVERNOR_FULL_M = 0.45 
FOLLOW_GOVERNOR_MIN_M  = 0.15  
FOLLOW_GOVERNOR_ARC_DEG = 25   

PATH_FOLLOWING_TARGET_REACH_DIST_PX = 4  
FOLLOW_WAYPOINT_STRIDE = 5                
FOLLOW_STUCK_MOVE_M = 0.005              
FOLLOW_STUCK_TURN_RAD = 0.03              
FOLLOW_STUCK_STEPS  = 25                  


FOLLOW_PROGRESS_WINDOW = 40   
FOLLOW_MIN_PROGRESS_PX = 3   
FOLLOW_MAX_RETRIES = 6       


FOLLOW_RECOVER_STEPS  = 25    
FOLLOW_RECOVER_VEL    = -0.12 
FOLLOW_RECOVER_OMEGA  = 1.2   
FOLLOW_MAX_RECOVERS   = 3     
FOLLOW_PROGRESS_WIN   = 45    
FOLLOW_MIN_PROGRESS_CELLS = 2 


FOLLOW_ALIGN_RAD   = 0.7      
FOLLOW_ALIGN_OMEGA = 2.5      

FRONTIER_MIN_CLUSTER       = 15   
FRONTIER_MIN_SIZE          = 20  
FRONTIER_MIN_DIST_PX       = 5    

FRONTIER_SELF_EXCLUDE_PX   = 12
FRONTIER_VISITED_RADIUS_PX = 30  
FRONTIER_SCORE_BIAS        = 15  

PILLAR_BIAS_WEIGHT         = 2.0

EXPLORATION_START_FRONTIER_AFTER    = 50  
EXPLORATION_FRONTIER_SELECTION_FREQ = 5   
EXPLORE_FREESPACE_RADIUS_PX         = 40  
EXPLORE_FREESPACE_TRIES             = 200 


EXPLORE_SCAN_TURN_TICKS      = 18   
EXPLORE_SCAN_TURN_WHEEL      = 4.0  
EXPLORE_FORGET_VISITED_EVERY = 6   

OBSTACLE_RECOVER_TURN_AFTER  = 2

SLAM_NUM_PARTICLES       = 30   
                                 
SLAM_ALPHA1              = 0.02  
SLAM_ALPHA2              = 0.02  
SLAM_ALPHA3              = 0.05  
SLAM_ALPHA4              = 0.01  
SLAM_SCAN_MAX_BEAMS      = 45    
SLAM_RESAMPLE_NEFF_RATIO = 0.5   
SLAM_LIKELIHOOD_SIGMA_M  = 0.08  
SLAM_REFINE_RADIUS_PX    = 2    
SLAM_REFINE_WINDOW_DEG   = 6.0   
SLAM_REFINE_STEP_DEG     = 2.0   
SLAM_OBSERVE_HZ = 10             
                                 

SLAM_OBSERVE_MIN_TRANS_M = 0.03   
SLAM_OBSERVE_MIN_ROT_RAD = 0.052 
SLAM_GREEN_PERIOD_STEPS = 3      


KEYFRAME_DIST_THRESHOLD_M      = 0.15  
KEYFRAME_ANGLE_THRESHOLD_DEG   = 15.0  
LOOP_CLOSURE_SEARCH_RADIUS_M   = 0.6   
LOOP_CLOSURE_MIN_KEYFRAME_GAP  = 15    
LOOP_CLOSURE_SCORE_THRESHOLD   = 0.06  
LOOP_CLOSURE_SEARCH_WINDOW_M   = 0.3   
LOOP_CLOSURE_SEARCH_STEP_M     = 0.033  
LOOP_CLOSURE_SEARCH_WINDOW_DEG = 20.0  
LOOP_CLOSURE_SEARCH_STEP_DEG   = 2.0    

LOOP_CLOSURE_COOLDOWN_KEYFRAMES = 20

LOOP_CLOSURE_ATTEMPT_INTERVAL = 8


RECOVERY_REVERSE_TICKS = 15   
RECOVERY_TURN_TICKS    = 20   
RECOVERY_REVERSE_VEL   = -0.1  
RECOVERY_TURN_OMEGA    = 1.5   


VIZ_PERIOD_STEPS = 5   


SEEK_LIN_VEL              = 0.20 
SEEK_OMEGA                = 0.40  
SEEK_BEARING_DEADBAND_RAD = 0.10  


PILLAR_COMMIT_DIST_M      = 1.0  
TARGET_REACHED_DIST_M     = 0.50  
APPROACH_OFFSET_M         = 0.30  
                                 

MISSION_MARK_RATIO        = 0.30  
MISSION_MARK_LASER_M      = 0.35 
MISSION_MARK_BEARING_RAD  = 0.25  
MISSION_MARK_MAX_STAMP_M  = 0.60 